import Head from 'next/head'
import Image from 'next/image'
import Articles from '../components/Articles'
import Conversations from '../components/Conversations'
import Editorials from '../components/Editorials'
import HeroOne from '../components/HeroOne'
import NewsletterOne from '../components/NewsletterOne'
import Photography from '../components/Photography'
import Production from '../components/Production'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J-J Project 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroOne />
      <Articles />
      <NewsletterOne />
      <Editorials />
      <Photography />
      <Conversations />
      <Production />
    </div>
  )
}
